### ISSUE TITLE
Error executing createPeerAdminCard.sh

### ISSUE THREAD

**Issue by ikumar6** [IBM/BlockchainNetwork-CompositeJourney#16]
I followed the steps all the way till executing the script ./createPeerAdmin.sh, I get the below error when i run this script. 

module.js:549
       throw err:
Error : Cannot find module './api'
at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
............

Tried upgrading npm package but didn't solve the issue.

**Comment by ljbennett62** [comment]
@ ikumar6 - so I just went through the pattern and did not run into the same error. My questions to you are:

Did you install the pre-reqs:
Dockerv1.13
npm V5.6.0 or higher
nvm 8.11.3 (**use nvm to install node**)
node 8.11.3
composer-cli@.19.5

I found it was very particular how you installed node and what version you used.

**Comment by ljbennett62** [comment]
You will need to uninstall composer, upgrade to node 8.9 and re-install composer. The reason is that composer depends on fabric node-sdk which depends on grpc. grpc is sensitive to the level of node you use, so by just upgrading node and not re-installing composer the version of grpc currently installed will not be the right one for node, so then you get the error you described.

**Comment by ikumar6** [comment]
ljbennett62 ,   Thanks for your response. It seems there was some issue
with the script/code given in the sample. i installed the composer by
following the steps provided on hyperledger website and could get this
sample running.

thanks
